### ISSUE TITLE
Deleting client credentials in the quick start form is broken

### ISSUE THREAD

**Issue by lpsinger** [tachgsfc/gcn.nasa.gov#129]
No logging output on the terminal or in the browser. Just... nothing happens.

https://user-images.githubusercontent.com/728407/176789428-dfe28061-6b16-47bd-ad02-92051c77681c.mov

**Comment by dakota002** [comment]
Should be resolved with this [PR](https://github.com/tachgsfc/gcn.nasa.gov/pull/133)
