### ISSUE TITLE
QuickStart widget - allow multiple notice formats

### ISSUE THREAD

**Issue by jracusin** [tachgsfc/gcn.nasa.gov#152]
Allow users to select multiple notice formats (text, VOEvent, binary).

**Comment by lpsinger** [comment]
I discussed this with @dakota002 a week or so ago, and I suggested not to implement this, because the sample code for the inside of the for loop (which is currently empty) will be different for different formats.

**Comment by jracusin** [comment]
Okay, that's fair.  People will have to generate multiple versions of the code for multiple formats.
