### ISSUE TITLE
GCN Circulars page: more prominent link to old GCN Circulars archive, add sufficient polish to make it public

### ISSUE THREAD

**Issue by lpsinger** [tachgsfc/gcn.nasa.gov#54]
The new GCN Circulars page is very obviously a placeholder and does not look polished enough to be public yet. Ultimately, it will need to reach feature parity with the old GCN Circulars archive, but before we get to that point it needs a certain je ne sais quoi to call it finished.

Some things that might be missing:

* Prominent link to archive
* Explanation of what GCN Circulars are
* Links to writing guide, code of conduct
* An example circular
* Maybe a tiny bit of dynamic content: link to most recent circular (that might be a task for Victor or Leo)

**Comment by eburnsastro** [comment]
I believe this can be closed. Evidently I should have marked "closes #54" in a commit for the pull request. I'll do this in the future
