### ISSUE TITLE
Primer on "what is kafka"

### ISSUE THREAD

**Issue by lpsinger** [tachgsfc/gcn.nasa.gov#57]
Add a little primer on "what is kafka". This probably goes partly on the main page and partly in the documentation.

_Originally posted by @jracusin in https://github.com/tachgsfc/gcn.nasa.gov/issues/56#issuecomment-1116462940_

**Comment by jracusin** [comment]
I just noticed that the deployment failed that resolves this issue.  Not sure how to fix this. @lpsinger @dakota002
