### ISSUE TITLE
Quick start guide for receiving alerts

### ISSUE THREAD

**Issue by lpsinger** [tachgsfc/gcn.nasa.gov#6]
Write a Quick Start guide with instructions for receiving alerts: signing up for GCN, creating a Client Credential, and configuring confluent-kafka-python.

**Comment by eburnsastro** [comment]
Tom Barclay, myself, and Josh Wood have tested with the easy to follow login instructions on test.gcn.nasa.gov and https://github.com/tachgsfc/gcn-kafka-python. Tom and I had no issues. Josh had a problem with the default Mac SSL settings and provided the below steps to resolve it. It may be worth including this on the page if we think it will be a reasonably common issue

I did a clean install again to run through the steps and make sure I got them all right:
install openssl with headers that we can compile against
    brew install openssl
2. add headers/lib to environment
  export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
 3. compile librdkafka against openssl installed with homebrew
 4. add to environment
export CPPFLAGS="$CPPFLAGS -I/path/librdkafka/install/include -L/path/librdkafka/install/lib"
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"/path/librdkafka/install/lib"
5. pip3 install gcn-kafka

**Comment by lpsinger** [comment]
@joshuarwood, would you please open an issue at https://github.com/tachgsfc/gcn-kafka-python/issues and describe the error that you encountered? I am curious if we can come up with a workaround that doesn't require building librdkafka from source.

**Comment by lpsinger** [comment]
Fixed now.

**Comment by lpsinger** [comment]
Closed in error, sorry.

**Comment by lpsinger** [comment]
Remaining installation issue is tracked as https://github.com/tachgsfc/gcn-kafka-python/issues/1.
