### ISSUE TITLE
Notice types on Swift mission page should use enum name

### ISSUE THREAD

**Issue by lpsinger** [tachgsfc/gcn.nasa.gov#68]
The Swift mission page should use the same machine-readble enum names as we use for Kafka topic names.

I am not sure how to do this for Swift because some of the notice types that are currently listed (like `XRT_PosNack`) seem to have no matching enum name.

See #67, https://gcn.gsfc.nasa.gov/filtering.html, and https://github.com/lpsinger/pygcn/blob/main/gcn/notice_types.py.

**Comment by jracusin** [comment]
XRT_PosNack should probably be on that filtering list, so also included in notice_types.py.

**Comment by lpsinger** [comment]
Does `XRT_PosNak` even exist?

**Comment by lpsinger** [comment]
I think that what PyGCN had called `SWIFT_XRT_CENTROID` is actually `SWIFT_XRT_POS_NACK`. See https://github.com/lpsinger/pygcn/pull/29.
